services:
  metabase:
    image: metabase/metabase:v0.50.8
    container_name: metabase
    env_file: ".env"
    ports:
      - "3000:3000"
    restart: always
    environment:
      JAVA_TIMEZONE: Asia/Kuala_Lumpur
      MB_ENCRYPTION_SECRET_KEY: ${METABASE_SECRET}
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: ${METABASE_PG_DBNAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_PG_USERNAME}
      MB_DB_PASS: ${METABASE_PG_PASSWORD}
      MB_DB_HOST: ${POSTGRES_HOSTNAME}
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./volumes/metabase-data:/metabase-data
      - ./volumes/plugins:/plugins
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      gdnet:
        ipv4_address: 10.10.17.51

networks:
  gdnet:
    name: garudanet
    external: true

