services:
  prometheus:
    image: 'prom/prometheus:v2.47.2'
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./volumes/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus/data:/prometheus
    networks:
      gdnet:
        ipv4_address: 10.10.17.41
    restart: always

  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:v0.47.2'
    ports:
      - 127.0.0.1:8180:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw

    networks:
      gdnet:
        ipv4_address: 10.10.17.43
    restart: always


networks:
  gdnet:
    name: garudanet
    external: true

