services:
  db:
    image: 'postgres:15.4-alpine3.18'
    env_file: '.env'

    ports:
      - 127.0.0.1:5432:5432

    volumes:
      - ./volumes/config:/tmp/config:ro
      - ./volumes/data:/var/lib/postgresql/data
      - ./volumes/init:/docker-entrypoint-initdb.d:ro

    networks:
      gdnet:
        ipv4_address: 10.10.17.2

    restart: always

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  gdnet:
    name: garudanet
    external: true

